title: Minh Nguyen # your name (or website title) here
logo: "anh the dep trai.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Data Scientist | BI Engineer
  <br><br>
  Seattle University ( 2019-2021) 
  <br><br>
  A data enthusiastic whose goal is to optimize efficiency and make the best use of limited resources. 
  Expertise in business intelligence, building statistical models, big data manipulation, and visualization. 
  Set the “Team” as the personal top priority and work with ethics, responsibility, credibility, and commitment to a strong result.
  <br><br>
  <a href="https://www.linkedin.com/in/huuminhn2206/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
