title: Minh Nguyen # your name (or website title) here
logo: "anh the dep trai.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst Intern 
  <br><br>
  Seattle University ( 2019-2021) 
  <br><br>
  <a href="https://www.linkedin.com/in/huuminhn2206/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minim
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
